### PR TITLE
Vaughn-README-FIX

### PR DESCRIPTION
**Pull request by CMVaughn**
My name is Christopher Michael Vaughn, I cleaned up the README by removing unnecessary whitespace, fixed some inconsistencies with unordered list, added brackets to links, removed an unnecessary Overview header from GitFlow Section and corrected Heading issues. Requesting review from project manager @reharri7

### CODE REVIEW

**Review by reharri7 — APPROVED** [review]
LGTM. Go ahead and merge this

**Comment by reharri7** [comment]
@CMVaughn Wait for the preview to pass. If it does, it will allow you to merge

**Comment by CMVaughn** [comment]
Awesome! The majority of the time it took me to do this was just figuring out how to do a pull request. Thanks for the easy task it really helped me get into the GitHub community!

**Comment by reharri7** [comment]
Resolves #9

**Pull request merged**
